// Code generated by "stringer -type=Operation node.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Plus-0]
	_ = x[Minus-1]
	_ = x[Not-2]
	_ = x[Eq-3]
	_ = x[Ne-4]
	_ = x[Le-5]
	_ = x[Ge-6]
	_ = x[Lt-7]
	_ = x[Gt-8]
	_ = x[Add-9]
	_ = x[Sub-10]
	_ = x[Mul-11]
	_ = x[Div-12]
	_ = x[Mod-13]
}

const _Operation_name = "PlusMinusNotEqNeLeGeLtGtAddSubMulDivMod"

var _Operation_index = [...]uint8{0, 4, 9, 12, 14, 16, 18, 20, 22, 24, 27, 30, 33, 36, 39}

func (i Operation) String() string {
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
